### PR TITLE
Push

### PR DESCRIPTION
**Pull request by amir**
Add Push MFA support

### CODE REVIEW

**Comment by andreyk0** [comment]
I'm not set up to test the new push feature but if you are happy with it - let's merge and I can publish updated binaries. Changes look good!

**Comment by amir** [comment]
Thanks! I asked a few people to try it as well and it seems to be working for them so I'm happy to merge if you are.

**Comment by gurghet** [comment]
@andreyk0 I create a release but I don’t have the private key to sign it. Could you go ahead and update the binaries please? Also how do you think it’s best to proceed to manage the keys from now on?
I can update the install script then.

**Comment by andreyk0** [comment]
Sure, in a little bit. Since we are re-building anyway I wanted to bump up stack lts.
Keys - perhaps a separate PR to include `CODEOWNERS` file to define shared repo ownership and add all owner's public keys to `install` ?

**Comment by amir** [comment]
@andreyk0 thanks for taking care of this release! The `CODEOWNERS` and addition of public keys of all of the owners to the `install` script sounds like the perfect solution. I'll create a PR for that soon.

**Comment by andreyk0** [comment]
Sounds good!
Ok, I've deleted `1.3` as it didn't follow tag naming convention and published `v1.3.1` that includes all changes and binaries.

**Pull request merged**
